### ISSUE TITLE
vrpc addon.cpp does not compile with most recent nodejs-devel 12.13.1

### ISSUE THREAD

**Issue by cstim** [bheisen/vrpc#5]
With most recent nodejs, addon.cpp does not any longer compile:

```
../node_modules/vrpc/vrpc/addon.cpp:224:39: error: no matching function for call to 'v8::Function::Call(v8::Local<v8::Primitive>, const unsigned int&, v8::Local<v8::Value> [1])'
  224 |     cb->Call(Null(isolate), argc, argv);
      |                                       ^
In file included from /home/cs/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../node_modules/vrpc/vrpc/addon.cpp:39:
/home/cs/.cache/node-gyp/12.13.1/include/node/v8.h:4193:43: note: candidate: 'v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)'
 4193 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(Local<Context> context,
      |                                           ^~~~
/home/cs/.cache/node-gyp/12.13.1/include/node/v8.h:4193:43: note:   candidate expects 4 arguments, 3 provided
```
The code in addon.cpp line 224 needs to be adapted to pass a Local<Context> as first argument, otherwise vrpc addons cannot be compiled with most recent nodejs. Thanks!

**Comment by bheisen** [comment]
addon.cpp compiles without warning for all versions of NodeJS >= 8
